#!/usr/bin/env bash
# ── 802 Manager — build number incrementer ────────────────────────────────────
# Called automatically by CMake before every compile (see CMakeLists.txt).
# Reads build_number.txt (= last completed build), increments to get the new
# build number, writes it back to build_number.txt, then writes src/Version.h.
# build_number.txt always equals the version the app was last built as, so
# the file and the window title / logfile always agree.
#
# To change major/minor version: edit VERSION_MAJOR / VERSION_MINOR below.
# Do NOT edit src/Version.h by hand — it is auto-generated and gitignored.
# ──────────────────────────────────────────────────────────────────────────────

set -e

VERSION_MAJOR=1
VERSION_MINOR=1

# Resolve repo root (script lives in <root>/scripts/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."
BUILD_FILE="$ROOT/build_number.txt"
VERSION_H="$ROOT/src/Version.h"

# Read last completed build number (default 0 if file missing or invalid)
PREV=$(cat "$BUILD_FILE" 2>/dev/null || echo "0")
[[ "$PREV" =~ ^[0-9]+$ ]] || PREV=0

# Compute new build number and write it back immediately (before compiling,
# so a failed compile still advances the counter and avoids number reuse)
BUILD=$((PREV + 1))
echo $BUILD > "$BUILD_FILE"

# Generate Version.h with the new build number
cat > "$VERSION_H" << EOF
#pragma once
// Auto-generated by scripts/bump_build.sh — do not edit manually.
// To change major/minor: edit VERSION_MAJOR/VERSION_MINOR in scripts/bump_build.sh.
// Build number is stored in build_number.txt (committed) and increments on every ninja run.

#define APP_VERSION_MAJOR  $VERSION_MAJOR
#define APP_VERSION_MINOR  $VERSION_MINOR
#define APP_VERSION_BUILD  $BUILD
#define APP_VERSION_STRING "$VERSION_MAJOR.$VERSION_MINOR.$BUILD"
#define APP_VERSION_FULL   "v$VERSION_MAJOR.$VERSION_MINOR.$BUILD"
EOF

echo "[802 Manager] Build v$VERSION_MAJOR.$VERSION_MINOR.$BUILD"
